export const CHECKOUT_CONST = {
  CONFIRMED_STATUS: 'completed',
  FAILURE_STATUS: 'failed',
  PARTIAL_CONFIRMED_STATUS: 'completedwithfailures',
  IN_PROGRESS_STATUS: 'inprogress',
  ORDER_CONFIRMED_STATUS: 'Confirmed',
  ORDER_PARTIAL_CONFIRMED_STATUS: 'PartiallyConfirmed',
  TOKENIZED_KEY: 'skfwefh$@fkew0fwy32ryr$#8ffjn3',
  ISSUEDBY: 'VI',
  USD: 'USD',
  INR: 'INR',
  NEW_TRAVELERPROFILE_OBJ: {
    label: 'New',
  },
  PHONE_LENGTH: 10,
  NAME_REGEX: '^[a-zA-Z]{1,25}$',
  ADD_ON_PRODUCT: 'insurance',
  NON_CLP: 'NonCLP',
  CLP: 'CLP',
  DROPDOWN_OPTION_NEW: 'NEW',
  EXPIRATION_DATE_MAX_DATE: 10,
  PAYMENT_MODE: 'card',
  POINTS_UNIT: 'points',
  MAX_EMAILS_ALLOWED: 5,
  FRAUD_CHECK_ERROR_CODE: '73',
  BOOKING_STATUS: 'orderConfirmation',
  LANDING_SCREEN: 'landing',
  CVV_MIN_LENGTH: 3,
  CVV_MAX_LENGTH: 4,
  CVV_REGEX: '^[0-9]{3,4}$',
  IS_AGENT: false,
  VALIDATE_BIN: true,
  BIN_FAILURE_MSG: 'Failed to perform Bin Validation',
  BIN_SUCCESS_MSG: 'Bin validation was successful',
  BIN_RETRY_COUNT: 2,
  IS_AGENT_OVERRIDE: false,
  OFAC_ENABLE: true,
  ORDER_FEE: 'orderFee',
  PRIMARY_PROFILE_TYPE: 'profile',
  SUB_PROFILE_TYPE: 'subprofile',
  ALLOWED_CARDS: ['visa', 'americanexpress', 'mastercard'],
  POINTS_VALUE: '50000',
  AMOUNT_VALUE: '$1000',
  TRAVELER_PROFILE_DROPDOWN_NAME : 'profiles'
};
